### ISSUE TITLE
is there a fork of LibreWolf WinUpdater for windows 7?

### ISSUE THREAD

**Issue by candrapersada** [adeii/supermium-portable#1]
is there a fork of [LibreWolf WinUpdater](https://codeberg.org/ltguillaume/librewolf-winupdater) to install and update the LibreWolf version?

**Comment by adeii** [comment]
Nope. You need to manually download new modded version. 
Or to update to latest official LibreWolf, but it won't install on older Windows than 10. 
So, you need to extract files again, edit Major(Sub)SystemVersion of librewolf.exe, and overwrite xul.dll and lgpllibs.dll from r3dfox.

**Comment by adeii** [comment]
> update the LibreWolf version

You can try the latest version 125.0.2:
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-125.0.2-1-win7-x64-portable.7z
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-125.0.2-1-win7-x86-portable.7z

**Comment by adeii** [comment]
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-125.0.3-win7-x64-portable.7z

**Comment by adeii** [comment]
New one https://github.com/adeii/supermium-portable/tree/F126
