### ISSUE TITLE
Remove frame

### ISSUE THREAD

**Issue by Jasantes** [adeii/supermium-portable#11]
Hi adeii, is there any way to remove the thick frame from the tab preview cards and extensions box? I looked for it in the flags but I didn't find it.

**Comment by adeii** [comment]
Hola Jasantes, 
Is this new problem with Firefox or Supermium? Maybe some line in *.js if Firefox. Can you show me some screenshot?

**Comment by Jasantes** [comment]
It's just an aesthetic issue in Supermium. 
As for tabs, I have disabled tab-hover-card-images. 
![Capture1](https://github.com/user-attachments/assets/21f561c2-2941-43b3-89a2-2f6ddc2b5b69)
![Capture2](https://github.com/user-attachments/assets/0446ff30-92f8-4bfb-b643-f5bcb4f09cad)

**Comment by adeii** [comment]
Already solved by author of Supermium browser, win32ss. https://github.com/win32ss/supermium
Try the latest build:
https://github.com/adeii/supermium-portable/releases/download/v124/supermium-portable-win64-124.0.6367-245-v3.7z

**Comment by Jasantes** [comment]
Ok, tx. I'll try it.
