### ISSUE TITLE
How to enable VxKex for Brave 1.64?

### ISSUE THREAD

**Issue by Jasantes** [adeii/supermium-portable#13]
https://github.com/adeii/supermium-portable/releases/tag/v1.64

**Comment by Jasantes** [comment]
**It's done, but...**

![Captura-2](https://github.com/user-attachments/assets/c49826b4-7c9d-40d8-b96d-350963e30f2a)

**Comment by adeii** [comment]
You should start browser with brave-portable*.exe or even brave-fix.bat.

Brave 128.1.69.x work with brave-fix.bat that is:
brave-portable32.exe --no-sandbox --enable-unsafe-webgpu --use-webgpu-adapter=d3d11
or try brave.exe --no-sandbox.

**Comment by Jasantes** [comment]
**NO WAY...**
brave-portable.exe (by Portapps) > **not working**
!NO_SANDBOX.bat > **not working**
**Before VxKex:**

![Brave-2](https://github.com/user-attachments/assets/58a067e0-d7e3-4fe2-b9d9-a10849b92362)

**Comment by adeii** [comment]
No need VxKex for 1.64/65/67, they are fully modded. You need it for 1.69.
