### ISSUE TITLE
Floorp browser

### ISSUE THREAD

**Issue by jasonliul** [adeii/supermium-portable#14]
It's a really surprise to Zen browser for win7. :)
Floorp is unique FF clone, try to make FF looks like Vivaldi, and have similar function.

Floorp
https://github.com/Floorp-Projects/Floorp/releases

Since v 11.17.x, Floorp based on FF 128 ESR, Win7 user has been abandon.
We just wonder, if you could make a Floorp for win7 user?
ehhhhhhhhhhhhhh, it's a big ask.

**Comment by adeii** [comment]
I could try. 
2-3 DLLs are from r3dfox project of the same version and few config lines, if you want to be compatible with Win 7.

**Comment by jasonliul** [comment]
Great news! thanks in advance.

Floorp never released x86 version, but provide a compile script for 32bit user.
https://github.com/Floorp-Projects/Floorp/blob/ESR115/.github/workflows/windows-build.yml

If you may, please also make a x86 version. :)

**Comment by adeii** [comment]
Floorp 11.7.17 works greatly but on Win 8.1 and Ubuntu 2024.

**Comment by jasonliul** [comment]
Weird, thanks for trying anyway.

**Comment by adeii** [comment]
Try this https://github.com/adeii/supermium-portable/releases/download/F1282/floorp-11.17.7-portable-x64-win7.7z
Made with libs from R3dfox 128.2 ESR x64. Seems to work, but no about:setup page with themes. Try pages from about:about to see what works.
x86 version should be compiled from the scrap, with Win 7 patches.

**Comment by jasonliul** [comment]
Wow, i'll ask more people to test.
Great job, man.

**Comment by adeii** [comment]
Sorry. It can not work on Win 7. Only on Win 8+.

**Comment by jasonliul** [comment]
Sad news, anyway, win8 works. :)

**Comment by adeii** [comment]
Can you try this the first, unfinished build of x86 Floorp? I do not have 32bit Windows to try, but it also works on Win 8 x64.
https://github.com/adeii/supermium-portable/releases/download/F1282/floorp-11.17.7-portable-x86-win8.7z

**Comment by jasonliul** [comment]
"Couldn't load XPCOM."

i use win7 x64.

**Comment by adeii** [comment]
> i use win7 x64.

Me, too! Enable VxKex for floorp.exe and try again! 
Or enable VxKex for flooorp.exe and start it with Floorp-portable.exe


![Screenshot_3](https://github.com/user-attachments/assets/f872e830-5d79-43ae-af49-48d11115e807)
Works on Win 7 x64 with VxKex. Works on Win 8 x64, after 3 crash errors.

**Comment by jasonliul** [comment]
Real good news, thanks for your insist. :)

**Comment by adeii** [comment]
> Real good news, thanks for your insist. :)

Download newer build, with fixed crash after 90 seconds 
https://github.com/adeii/supermium-portable/releases/download/F1282/floorp-11.17.7-portable-x86-VxKex.7z

**Comment by jasonliul** [comment]
OK.

**Comment by adeii** [comment]
This could interest you - new Floorp for Win 8
https://github.com/adeii/supermium-portable/releases/download/F1282/floorp-portable-11.18.1-x64-win8.7z

x86 Floorp is built, but does not work yet.

**Comment by jasonliul** [comment]
Wow, a good gift for weekend.:)

**Comment by adeii** [comment]
Get VxKex ready for https://github.com/adeii/supermium-portable/releases/download/F1282/floorp-11.18.1-portable-x86-VxKex.7z

**Comment by jasonliul** [comment]
Have a nice weekend, my friend.

**Comment by adeii** [comment]
You too!
