### ISSUE TITLE
zen-browser-1.0.0.0-a29-x64-win7 does not start in Win 7.

### ISSUE THREAD

**Issue by EDSln** [adeii/supermium-portable#15]
![Error](https://github.com/user-attachments/assets/59242229-ef6b-4edb-b02a-a4e811cbdae4)
Platform update and C++ 2015-2022 are installed.

**Comment by adeii** [comment]
No problem. Add this libs to root folder 
https://github.com/adeii/supermium-portable/releases/download/F1282/Win7-System32-DLL-for-NewGame-NewEmu.7z

**Comment by EDSln** [comment]
Now another error. VxKex required?
![Error2](https://github.com/user-attachments/assets/d4aef554-80d1-4542-a65c-e07b333bd4a9)

**Comment by adeii** [comment]
> Now another error. VxKex required?

Да. Вы правы. VxKex необходим.

**Comment by adeii** [comment]
https://github.com/adeii/supermium-portable/releases/download/F1282/zen-browser-1.0.0-a33-x64-VxKex.7z

**Comment by EDSln** [comment]
Is VxKex integrated here? Still an error.
![error](https://github.com/user-attachments/assets/f547c8a5-eace-435a-8c8c-b32b295a7243)

**Comment by adeii** [comment]
No. You need to install VxKex and check "Enable VxKex for this program" in VxKex tab in Properties for zen.exe.
One of valid copy of VxKex could be found here:
https://github.com/i486/VxKex/releases/download/Version1.1.1.1375/KexSetup_Release_1_1_1_1375.exe

**Comment by EDSln** [comment]
Да, с VxKex работает.
