### ISSUE TITLE
Firefox: Style tabs in Developer Tools don't work

### ISSUE THREAD

**Issue by narinishi** [adeii/supermium-portable#17]
For example, when clicking on 'Computed', the whole section goes blank.
![image](https://github.com/user-attachments/assets/5d54aff8-48db-4758-93e4-a8b49b451319)

Firefox: 129 x64
Windows: 8.1 x64

**Comment by adeii** [comment]
Firefox on 8.1 is easy to mod. Just change Major...SystemVersion from 000A to 0006 with CFF explorer and no need for r3dfox DLLs. Try the latest FF 130 beta 9: <uploading>
