### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Jasantes** [adeii/supermium-portable#18]
**Hi adeii, is there any solution for this warning?:
The --no-sandbox command line flag is not supported... or something like that on every startup.**
![Capture-1](https://github.com/user-attachments/assets/36aac64c-9d6d-4ae4-922b-7fda80dcc108)
**How to remove --no-sandbox so that the warning does not appear?
Thank you in advance.**
![Capture-2](https://github.com/user-attachments/assets/e1805a0e-4277-47c2-8c2e-b127c956a587)

**Comment by adeii** [comment]
StackOverflow answer says to add flag --test-type after --no-sandbox.
