### ISSUE TITLE
Password manager not working

### ISSUE THREAD

**Issue by Jasantes** [adeii/supermium-portable#19]
**Hi adeii, when I add a pw or import csv file, the password manager does not record any change, even in the same session. 
I don't know what to do anymore: I tried disabling clear-data-on-exit and even reinstalled portable, but nothing worked. Thank you in advance.** 
![Capture-1](https://github.com/user-attachments/assets/2d5adf0d-cdc9-4e68-89fe-aa395a18a882)
![Capture-2](https://github.com/user-attachments/assets/5b1e6139-86c4-441e-af37-35e29fe1c48c)
**Details:**
![Capture-3](https://github.com/user-attachments/assets/ee557392-dc8b-4e90-83ff-538a50666b81)

**Comment by adeii** [comment]
Does official Supermium have the same error? I just make portable versions of them.

**Comment by Jasantes** [comment]
Ok, I could solve it by installing the official version. 
BTW, I' be grateful if you can clarify this doubt: 
If I sync with my Google account, can this affect my Google Chrome settings?

**Comment by adeii** [comment]
Well, hotfixed version seems has working Pass Manager.
Syncing empty browser with Google should not mess your Chrome setting.
But after sync, every change will affect.
