### ISSUE TITLE
Chrome 125.x 64bit on Win 8.1 not working

### ISSUE THREAD

**Issue by narinishi** [adeii/supermium-portable#2]
It can't find DWri32.dll. When I try copying this file to the correct directory, the browser window only briefly displays before closing.

**Comment by adeii** [comment]
Does Brave x64 work on your Win 8.1 ? It seems easier to run. All added files there are the same as for Chrome.

**Comment by narinishi** [comment]
[brave-portable-win32-123.1.65.101.7z](https://github.com/adeii/supermium-portable/releases/download/v1.64/brave-portable-win32-123.1.65.101.7z) works

How do I get x64 version?

**Comment by narinishi** [comment]
Okay, I found Brave x64 [Chrome 125.x 64bit on Win 8.1](https://github.com/adeii/supermium-portable/releases/tag/C125)

It does not work. The window briefly displays but it is white inside, and then it closes.

**Comment by adeii** [comment]
> It does not work. The window briefly displays but it is white inside, and then it closes.
I can tell you on Monday version and updates for Win 8.1 x64 on what Chrome/Brave works. I guess that some security for Win and/or the latest VC++ runtimes missing.

**Comment by narinishi** [comment]
Can you show me in Control Panel Programs and Features which Visual C++ redistributables are installed?

**Comment by narinishi** [comment]
Never mind, using Process Monitor I was able to find out that the missing file was `API-MS-WIN-CORE-REALTIME-L1-1-1.dll`
I was able to copy it from a different version of Chrome and it worked. Would you be able to include this file in future releases?

**Comment by adeii** [comment]
> API-MS-WIN-CORE-REALTIME-L1-1-1.dl

Thank you for solving missing lib. I will include it.
