### ISSUE TITLE
Vivaldi 6.9.3447.46 x86 for Win 7 does not run on 8.1 (x64).

### ISSUE THREAD

**Issue by Someone-G** [adeii/supermium-portable#22]
Vivaldi 6.9.3447.46 x86 for Win 7 does not run on 8.1 (x64).
![2024-09-19 09 43 14](https://github.com/user-attachments/assets/109be208-7193-4584-83d6-f8aa65153002)

The requirements require need VxKex 1.1.1+, but it does not download - the browser blocks the download because it considers the file dangerous. Plus Comodo IS also responding to this file. Is this how it should be? I have never encountered this software.

**Comment by Someone-G** [comment]
![2024-09-19_102812](https://github.com/user-attachments/assets/fb419fa6-61e5-4be0-bb4f-6b932eeb8aa4)

**Comment by adeii** [comment]
I am just considering the same problem. VxKex is not a virus, unless to had downloaded from shady site.
Vivaldi 6.9 x86 nor x64 works on Win 8.1. You can use 6.8.3381.x for now.

**Comment by Someone-G** [comment]
I didn't see version 6.8.3381.x here.
Here I found the vivaldi-portable version-6.6.3271.61.x64-win8.7z, but it does not start either.

**Comment by adeii** [comment]
Maybe some of this?
https://github.com/adeii/supermium-portable/releases/download/C125/vivaldi-portable-win32-6.7.3329-35-win7.7z

https://github.com/adeii/supermium-portable/releases/download/C125/Vivaldi-portable-win64-6.7.3329.39-win8.7z

https://github.com/adeii/supermium-portable/releases/download/v6.5/vivaldi-6.8.3381.44-x86-win7.7z

**Comment by adeii** [comment]
Hello @Someone-G ,
Can you try this version of Vivaldi on Win 8.1?  No VxKex this time!
https://github.com/adeii/supermium-portable/releases/download/v6.9/Vivaldi-7.0.3495.11-x86-Win7.7z

**Comment by Someone-G** [comment]
> Hello @Someone-G , Can you try this version of Vivaldi on Win 8.1? No VxKex this time! https://github.com/adeii/supermium-portable/releases/download/v6.9/Vivaldi-7.0.3495.11-x86-Win7.7z

Hello. It doesn't start. I tried to run it as an administrator - there is no effect.
![2024-11-09_224722](https://github.com/user-attachments/assets/a6e9a20c-936c-4dab-b5e8-0135f11c2e2b)

**Comment by Someone-G** [comment]
> Did you tried to run it via vivaldi.bat or vivaldi.exe --no-sandbox ?
At first I started vivaldi.exe - it didn't work.
Then I created a shortcut for vivaldi.exe and in the line "Object" (file path) I added the key "--no-sandbox" - everything worked. The browser is working stably. There was not a single problem.

**Comment by adeii** [comment]
Thanks for reply and good news!
Also add "--test-type" to hide popup-bar about low security without sandbox.
