### ISSUE TITLE
antiviruses detect kernel64.dll as a malware

### ISSUE THREAD

**Issue by ahahahaah** [adeii/supermium-portable#23]
hello
i wanted to try vivaldi for win7 portable, but when i uncompress the archive,  my antivirus detects it immediately as a malware
so i analysed it with the website totalvirus.com, and there, many anvitiruses detect it as a malware
so is it possible to have an other version of kernel64.dll?
(i can find kernel32.dll for download on internet but not kernel64.dll)

**Comment by adeii** [comment]
False positive. Add kernel64.dll as an exception.
Kernel64.dll is custom build of kernel32.dll by Blaukovitch, it is Win7 kernel lib with many added methods from Win 8/10.
