### ISSUE TITLE
firefox 132 doesnt work but 130 does.

### ISSUE THREAD

**Issue by ahahahaah** [adeii/supermium-portable#24]
hello
i've checked this page https://github.com/adeii/supermium-portable/releases/tag/F130
i've got win7 and firefox 130.0.1 works without issue in a sandbox.

(i precise that i choose the releases of this project because the versions of r3dfox don't work when i want to run them in a sandbox)

yesterday i've tryed firefox 132.0b9 and it has the same behaviour than r3dfox while 130.0.1 doesn't. I mean, 132 doesnt work within a sandbox but 130.0.1 works perfectly.
Is there an important thing that changed in the v132 that makes the issue?

**Comment by adeii** [comment]
Which one of 130.0.1 works perfect x64 or x86?

**Comment by ahahahaah** [comment]
x64 :)

**Comment by adeii** [comment]
So another beta version got some bug.
Guess this release will solve this 
https://github.com/adeii/supermium-portable/releases/download/F130/Firefox-portable-132.0-x64-Win7.7z

**Comment by ahahahaah** [comment]
dude you are awesome !!!

**Comment by adeii** [comment]
Thanks!
