### ISSUE TITLE
how to get `VxKex` portable without installation?

### ISSUE THREAD

**Issue by candrapersada** [adeii/supermium-portable#25]

**Comment by adeii** [comment]
IMHO that is not possible. 
You can TRY to copy Kx***.dll to app's folder and replace original DLLs in Import folder with Kx***.dll via CFF Explorer for certain *.exe and few *.dll. Do not forget to copy C:\Windows\System32\KexDll.dll
Example: ntdll.dll -> KxNt.dll,  ws_2.dll -> KxNet.dll, kernelbase.dll -> KxBase.dll, AdvApi32.dll -> KxAdvApi.dll...

**Comment by thinkpad4** [comment]
@adeii could you provide a link to the latest stable version of VxKex you use please?  There are so many repositories it's hard to find the real safe one.  Thank you very much

**Comment by adeii** [comment]
Legal successor of original VxKex is:
https://github.com/i486/VxKex/releases/tag/Version1.1.1.1375

Even newer fork of VxKex is named MgKex:
https://github.com/Aqua-Vision/MgKex/releases

I am currently using MgKex 1.1.1.1381.

**Comment by thinkpad4** [comment]
Thanks
