### ISSUE TITLE
Latest Zen browser on Windows 8.1

### ISSUE THREAD

**Issue by wealstarr** [adeii/supermium-portable#26]
Hello,

Extremely grateful to you for enabling us to use updated browsers on older unsupported Windows, your work means a lot. 
So the new Firefox 133 has some major improvements which greatly enhance the browsing experience for Dark Reader users. I tested it and really liked it, but I couldn't get it to work without breaking my system.

I grabbed the latest Zen twilight build [Twilight build - 1.0.2-t.2](https://github.com/zen-browser/desktop/releases/tag/twilight), replaced the .dll files you taught me in another repo from r3dfox version 133 and it worked.

I checked PDF, pass
Youtube, pass
Live streaming websites, pass
Some other random sites, pass
But as soon as I got to Reddit, some warning about Dark Reader appears, and before I could do anything about it, it crashed my Intel display driver. I had to restart and work my way around to be able to uninstall and then reinstall the Intel driver, which brought everything back to normal. But I didn't dare to try again as I'm on custom Windows build for older systems which doesn't have system restore or last known good configuration options.

I'm assuming if Reddit is exempted from Dark Reader, it might work, but still needs thorough investigation and testing. Can't have display adapter crashing often.

Plus, I checked the information page `about:support`, it said under codecs that only H264 decoding was available through software and hardware. All the rest of the codecs were listed as Not Supported. This is not the case in Firefox 132. Apart from HEVC, all the rest codecs are listed as decoding supported through software.

So what does this mean ? And what could be done to be able to use the newest Zen on Windows 8.1 ? Would really like to switch, if you could help us get there. Your help will be highly appreciated.

Kind regards

**Comment by adeii** [comment]
Sorry, but the latest Zen 1.0.2 twilight can not run on Win 7 with VxKex nor Win 8.1, yet. 
The first problem is missing of api-ms-core-version-l1-1-1.dll (could be found in Office 365 (2019)) than few function like ...SizeW, but our OS got files with ...SizeExW or ...SizeExA and there is no space for replacing function names. We could still use Zen 1.0.1.

**Comment by adeii** [comment]
XUL.dll from PlasmaFox 133 does not have codecs, but original XUL.dll from Firefox has them.
Maybe it will work on Win 8.1, since works on Win 7 with extended kernel.
https://github.com/adeii/supermium-portable/releases/download/F132/Firefox-portable-133.0.3-x64-VxKex.7z
![Screenshot_2](https://github.com/user-attachments/assets/6ff3aa16-3d04-45c9-8c0e-cec916532678)

**Comment by wealstarr** [comment]
> Sorry, but the latest Zen 1.0.2 twilight can not run on Win 7 with VxKex nor Win 8.1, yet. The first problem is missing of api-ms-core-version-l1-1-1.dll (could be found in Office 365 (2019)) than few function like ...SizeW, but our OS got files with ...SizeExW or ...SizeExA and there is no space for replacing function names. We could still use Zen 1.0.1.

Hi, thank you for the response. Actually, Zen 1.0.2 worked on 8.1, initially it gave some errors regarding the ms-core...dll's but I got around the problem by copying and renaming plasmafox.exe launcher to zen.exe, not without issues though, some Zen mods worked, some didn't like remove browser padding and remove rounded corners etc.

Had that Reddit+Dark reader issue not arise, I would have moved on to working out, how to get those Zen mods working. The two I mentioned are essential for my workflow.

I'm assuming Zen 1.0.1 is based on Firefox 132 ? If that's the case, it will defy the entire reason to upgrade as I want Zen based on Firefox 133.

Thank you for your explanation about the codecs. I watch Youtube and Sports streaming websites, so long they work without burning my CPU, I'm good.

I'm assuming, as long as x264 is working, no other codecs are needed for youtube and sports streaming? Sorry, kinda noob about this stuff.

Also, where can I find the extended kernal for Windows 7? and is there such a thing exists for 8.1 too ?

Thank you, Mr. adeii, your help and continued support is highly appreciated. Thank you for being with us and doing this for us. I would still be using 115, if it wasn't for your expertise and commitment.

**Comment by wealstarr** [comment]
> > copying and renaming plasmafox.exe launcher to zen.exe
> 
> Very neat solution. Bunch of modules are in xul.dll, so there is no zen modules in plasmafox xul.dll. Yes, Zen 1.0.1 is based upon FF 132. No extended kernel for Win 8.x :( For Win 7, there are - VxKex software by i486 and - modded kernel files by dotexe1337. Better is to try to mod x86 version of FF 133 or wait for solutions from r3dfox 133 developers or for Blaukovitch to mod some FF 133-based browser.

Thank you for the response, Mr. adeii

If it wasn't crashing my display driver, I would be inclined again with new information you have provided, but alas! I can't as I mentioned before, there's no recovery in my custom build Windows so if something goes wrong beyond recovery, the only way is to re-install Windows with all the custom settings, hours and hours of installing and configuring applications, something I'm not ready to do unless there's no other way.

Plasmafox 133 is based on Firefox 133 and works as intended, the only reason I wanted Zen is because of those vertical tabs I got so use to and Firefox is still far away from implementing them with all the necessary options which Zen already provides by the way.

I also tried Sideberry addon but even though they have many options still some very basic things are missing like not being able to keep the tabs on the sidebar collapsed at all time, hovering or otherwise. Zen allows me to do this, hence my inclination towards it.

The issue with Reddit+Dark reader also occurs in Zen 130 but it doesn't crash anything, just the page hangs on along with a warning from Zen that Dark reader is slowing system down. I made an exception to Reddit and it's all happy ever after.

I will keep an eye on your repo and seriously hope that you find a way to get the latest Zen working on 8.1 or I'll be stuck on the current version forever unless I purchase a new computer.

Thank you for your contributions and your kind support. God doesn't answer my prayers but I will pray for your happiness nonetheless.

Kind regards

**Comment by wealstarr** [comment]
Update:

I see you have posted Zen 1.0.2 but I couldn't get it to work as VxKex doesn't work with Windows 8.1, error log said, couldn't import .reg files.

I also tried to use the API and other files from your package into latest Zen downloaded from its repo, but it threw error too.

**Comment by adeii** [comment]
It does not work even on Win 7 with VxKex, just open shell, but can not open web pages. Abandon version for now.
BTW Zen 1.0.1 is built upon FF 131 not 132.

**Comment by wealstarr** [comment]
> It does not work even on Win 7 with VxKex, just open shell, but can not open web pages. Abandon version for now. BTW Zen 1.0.1 is built upon FF 131 not 132.

Thank you again for the response, Mr. adeii

That's too depressing. Apparently, gonna have to wait until Mozilla figures out all the options necessary to make the vertical tabs work. It may be version 140 or even 150, those guys are really slow. So basically sticking with the current Zen is the path forward unless there's an opening and you get newer Zen to work. I do hope you succeed. It's not just me benefitting from your work, I've suggested your repo on MDL forums and now I see people regularly linking to your custom releases.

Thank you for doing this for us. And may Allah bless you with all his blessings.

Kind regards

**Comment by wealstarr** [comment]
> There is a new hope! FF 133 works on Win 7/8 https://github.com/Blaukovitch/Mozilla_Firefox_Windows_7/releases/tag/FURRYFOX_3
> 
> Thanks to grand master @Blaukovitch and his bithack-fu, you can use Zen 1.0.2 on Win 7/8. https://github.com/adeii/supermium-portable/releases/download/F132/zen-portable-1.0.2-b5-x64-Win7.7z

ohhh, that's great news, Mr. adeii

Thank you, Mr. adeii, everything works perfectly. PDF, Youtube, codecs, all is well. No crashes or hangs.

Edit: remove browser padding mod doesn't work. Is there any way to get around the problem?
Here's the link for the mod
https://zen-browser.app/mods/680424a8-a818-406b-98c5-7726214e2a9f/

**Comment by adeii** [comment]
You are welcome.
I guess that mods just change theme mjs/css/js. Somewhere in browser/omni.ja

**Comment by adeii** [comment]
Dear friend,

Since Theophania is day for good news, I got one for you - New Zen 1.7b is ready for Win 7/8.
https://github.com/adeii/supermium-portable/releases/download/F134/zen-portable-1.7.0-b1-x64-Win7.7z

**Comment by adeii** [comment]
@wealstarr 
Dear friend,
You can try new Zen 1.7.6b on Win 8.1.
https://github.com/adeii/supermium-portable/releases/download/F135/zen-portable-1.7.6-x64-win7.7z
