### ISSUE TITLE
Blaukovitch Chrome repo suspended

### ISSUE THREAD

**Issue by narinishi** [adeii/supermium-portable#3]
repo https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/

Do you know if these releases will be made available elsewhere? You mentioned Blaukovitch with Blaukovitch.

**Comment by adeii** [comment]
> Do you know if these releases will be made available elsewhere?
Repo is suspended for all Chrome/Chromium and Google Egde modds.
You can find mirrors of his release on forums like MyDigitalLife -dot- net but you need to login. Any new info will appears here: https://github.com/Blaukovitch/API-MS-WIN_XP/issues/2
