### ISSUE TITLE
Librewolf - about:config

### ISSUE THREAD

**Issue by tutak-kat** [adeii/supermium-portable#5]
Hi, any idea why there is a problem with about:config?
Any possible solution?
Thanks

**Comment by adeii** [comment]
Since xul.dll are copied from r3dfox, try about:confignew .
Even could try LF 126.0.1 instead LF 126.0: 
https://github.com/adeii/supermium-portable/releases/download/F126/librewolf-126.0.1-windows-x64-portable.7z

**Comment by tutak-kat** [comment]
Hi, I just try to run your new portable Librewolf 126.0.1 size 174 MB (big increase in size?) on Win 7x64 and got error: 
Can't load XPCOM.

When I was trying to prepare latest Librefwolf 126.0.1 with necessary files from r3dfox (also latest version from 2 days ago) I got the same error and also this one - The procedure entry point EventSetInformation could not be located in the dynamic link library ADVAPI32.dll.
So I'm unable to run r3dfox and Librewolf on windows 7x64.

Any ideas?
Thanks

**Comment by adeii** [comment]
Does at least r3dfox 126.0 work on your Win 7 x64, since 126.0.1 does  not? If not, seems that problem is in some missing DLL.

**Comment by tutak-kat** [comment]
Hi,
you can close this issue since I tried it in vmware and got those errors because last time when I tried ver 126 on real PC I lost my Librewolf profile. Now I tried portable versions on win 7 x64 your and 3rdfox versions and both worked correctly.
Probably some libraries are missing in my virtual machine.
Sorry for confusion

**Comment by adeii** [comment]
No problem. I am glad that it works. You could try Tenorshare 4DDiG DLL Fixer to add various DLLs and .NET and VC++ Runtimes to system (real and virtual).
