### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by ahahahaah** [adeii/supermium-portable#7]
hello
i've just discovered this project. 
i have seen a portable version of firefox for windows 7, i wanted to ask how works the update process?

for the next major release, the check new version option works as the normal version or should i download the new portable version zip file and import the addons and preferences etc... from the previous version?
thanks

**Comment by adeii** [comment]
Hello,
Thanks for reply.
There is no automatic update at all. New major version will be released here, you just need to overwrite files from new *.7z to older FF folder. 
FF 128.0 will be uploaded soon.

**Comment by ahahahaah** [comment]
thanks for the answer :D
