### ISSUE TITLE
Firefox releases have r3dfox user agent

### ISSUE THREAD

**Issue by narinishi** [adeii/supermium-portable#8]
Notably, this impacts

- https://www.google.com/ - returns basic HTML version as it doesn't consider the browser modern
- https://addons.mozilla.org/en-US/firefox/ - makes page think browser isn't Firefox

**Comment by adeii** [comment]
What version of FF/LW makes that problem?

**Comment by narinishi** [comment]
I am using 128.0 (64-bit)

**Comment by adeii** [comment]
Thanks for founding new bug. It will be solved in further releases.
Quick Fix: Open **about:confignew** in Firefox, search for parameter **general.useragent.compatMode.firefox** switch it from false to true. Now works with Mozilla addons.

**Comment by useribs** [comment]
Cannot reproduce in 129.0 (64-bit), probably fixed
