### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by sikongconglu** [adeii/supermium-portable#9]
Why does this browser display the status of logging out of my Google account when I open a link through third-party software after setting it as the default browser？

**Comment by adeii** [comment]
Which browser? 
- Supermium? I don't know. I just made portable version of it.
- Some other Chromium browser? I try to make it works on Win 7 and than portable.
- Firefox/LibreWolf? Still not know. Libs are from r3dfox project, rest is originally from Mozilla Firefox.

**Comment by sikongconglu** [comment]
Just Supermium-Portable Browser. When you set it as the default browser in the browser settings, opening a link from third-party software will default to calling chrome.exe instead of supermoum-portable.exe, which still results in creating a personal data folder in the local folder.

**Comment by adeii** [comment]
Is this version have that problem?  https://portableapps.com/apps/internet/supermium-portable
This should be older but official, mine is not.
